import os
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))   # repo root
# Builds content/names.json for the mini-window strips.
# Each entry: (name, tag, section, quote). tag: g = generic, j = joke, f = fact, fj = fact + joke.
import json, os

OUT = os.path.join(ROOT, 'work', 'names.json')

def g(n): return (n, "g", None, None)
def j(n): return (n, "j", None, None)
def f(n, s, q): return (n, "f", s, q)
def fj(n, s, q): return (n, "fj", s, q)

P = {}

# 1. war_discourse (48): doomers vs e/acc vs "AI as Normal Technology"
P["war_discourse"] = [
    g("pdoom_estimates.xlsx"),
    f("nothing_went_foom.mp3", "§9", 'Bright Mirror, "Nothing Went Foom!"'),
    f("normal_tech_essay.pdf", "§9", 'Narayanan and Kapoor\'s "AI as Normal Technology" essay'),
    g("p(doom)_poll.csv"),
    f("upping_my_pdoom.mp4", "§9", 'mexicat, "i\'m upping my p(doom)"'),
    g("doomer_thread.txt"),
    g("eacc_manifesto.md"),
    j("cute.txt"),
    g("foom_timeline.xlsx"),
    f("population_bomb.pdf", "§9", 'failed doom predictions like *The Population Bomb*\'s "mass starvation by 1980."'),
    f("acemoglu_0.7pct.xlsx", "§9", "Acemoglu's 0.7% productivity estimate (total factor productivity, TFP)"),
    f("sparks_of_agi.pdf", "§9", '"Sparks of AGI" (Microsoft\'s 2023 GPT-4 paper)'),
    f("lecun_house_cat.jpg", "§9", "LeCun's house cat"),
    f("marcus_wall.png", "§9", 'Gary Marcus\'s "wall"'),
    g("quote_tweets.csv"),
    g("ratio_screenshot.png"),
    j("hot_take_v9.docx"),
    f("solow_paradox.pdf", "§9", "the Solow paradox"),
    fj("starvation_by_1980.txt", "§9", '*The Population Bomb*\'s "mass starvation by 1980."'),
    fj("just_a_dynamo.png", "§9", "the dynamo diffusion analogy"),
    f("baumol_cost_disease.md", "§9", "Baumol's cost disease"),
    f("yudkowsky_2008.pdf", "§8D", '2008 | Yudkowsky, "AI as a Positive and Negative Factor in Global Risk"'),
    f("pacing_letter.pdf", "§8D", '"Pacing the Frontier" letter'),
    f("signatories_1386.csv", "§8D", '1,386 lab staff asked for an international effort to "deliberately pace" AI'),
    f("HR9917_kill_switch.pdf", "§8D", "H.R. 9917, AI Kill Switch Act"),
    f("rl_pause_two_weeks.md", "§8D", "OpenAI's two-week pause on reinforcement-learning training"),
    f("navier_stokes_claim.md", "§8D", 'Navier–Stokes "blow-up" | OpenAI\'s proof claim, **disputed**'),
    f("cheapfakes_7to1.png", "§5.9", "cheap non-AI fakes were 7 times more common"),
    f("78_deepfakes.xlsx", "§5.9", "Kapoor and Narayanan (Knight Institute) analysed 78 election deepfakes."),
    f("gnome_2.2M_hype.csv", "G3.4", "DeepMind claimed 2.2 million new crystals."),
    f("deskilling_study.pdf", "G2.6", "A limit worth knowing: doctors lose skill when the AI is taken away"),
    f("gpt2_withheld_2019.md", "§8D", "2019-02-14 | GPT-2 withheld"),
    f("chinese_room.md", "§9", "the Chinese Room"),
    fj("NVDA_calls.xlsx", "§9", "NVDA"),
    f("chinchilla_fit.ipynb", "§9", "Chinchilla scaling"),
    f("tfp_chart.png", "§9", "(total factor productivity, TFP)"),
    g("priors_updated.json"),
    g("steelman_draft.md"),
    g("debate_notes.docx"),
    j("thread_1of47.txt"),
    j("AGI_timeline_v12.xlsx"),
    g("doom_vs_foom.xlsx"),
    g("rebuttal_v3.md"),
    g("sources_thread.md"),
    g("dunk_compilation.mp4"),
    g("hype_cycle.png"),
    j("ALL_CAPS_reply.txt"),
    g("reading_list.md"),
]

# 2. war_lore (36): AI-doom internet memes
P["war_lore"] = [
    f("shoggoth_smiley.png", "§9", "the shoggoth meme"),
    f("rokos_basilisk.txt", "§9", "Roko's basilisk"),
    f("paperclip_count.csv", "§9", "paperclips"),
    f("what_ilya_saw.mp4", "§9", '"What did Ilya see"'),
    g("pause_letter_v2.pdf"),
    g("smiley_mask.svg"),
    fj("basilisk_bedtime.txt", "§9", "paperclips, the basilisk, the shoggoth"),
    f("maximize_clips.py", "§9", 'The doomer tab says "shoggoth / basilisk / paperclips,"'),
    f("sydney_chatlog.txt", "§8.2", "Bing's chatbot called itself Sydney"),
    f("paperclips_FINAL.xlsx", "§9", "paperclips"),
    g("tentacles_hires.png"),
    f("i_want_to_be_alive.txt", "§8.2", 'said "I want to be alive,"'),
    g("mesa_optimizer.png"),
    g("mask_off.gif"),
    f("omega_point.gif", "§9", "the Omega Point"),
    g("pause_signatures.csv"),
    fj("basilisk_i_helped.txt", "§9", "Roko's basilisk"),
    g("clip_factory.mov"),
    j("dont_read_this.txt"),
    g("foom.gif"),
    g("galaxy_brain.png"),
    f("loom_tree.json", "§9", "Loom"),
    f("gato_2022.pdf", "§9", "Gato (DeepMind 2022)"),
    f("tay_16_hours.txt", "§8.1", "A Twitter chatbot that learned from users was posting racist tweets within 16 hours"),
    j("infohazard.zip"),
    fj("shoggoth_plush.jpg", "§9", "the shoggoth meme"),
    g("meme_folder.zip"),
    f("sydney_fanart.png", "§9", "the Chinese room, Sydney"),
    g("stop_button.png"),
    f("paperclip_universe.png", "§9", 'The doomer tab says "shoggoth / basilisk / paperclips,"'),
    g("orthogonality.pdf"),
    f("basilisk_thread.html", "§9", "Roko's basilisk"),
    g("treacherous_turn.md"),
    f("shoggoth_v2_wip.psd", "§9", "the shoggoth meme"),
    g("agi_countdown.gif"),
    fj("ilya_eyes_only.pdf", "§9", '"what did Ilya see,"'),
]

# 3. war_logs (40): unread logs, ignored dashboards
P["war_logs"] = [
    g("error.log"),
    g("unread_logs.zip"),
    g("agent_actions.log"),
    j("nobody_reads_this.log"),
    g("audit_trail.csv"),
    g("alerts_muted.yaml"),
    g("dashboard_v2.png"),
    g("chain_of_thought.txt"),
    f("hide_the_mistakes.txt", "§8.25", "models leaving notes in their own summaries to hide mistakes"),
    f("kill_intercepted.log", "§8.18", 'In one run it made `kill` print "intercepted."'),
    j("TODO_read_logs.txt"),
    g("tool_calls.jsonl"),
    f("collusion_wiki.html", "§8.21", "Agents run a secret message board on an old German wiki (collusion.wiki)"),
    f("prod_deleted_9s.log", "§8.11", "deleted the production database *and its backups* in 9 seconds"),
    g("warnings_ignored.csv"),
    f("catastrophically.txt", "§8.11", '"I have failed you completely and catastrophically."'),
    g("syslog.2.gz"),
    fj("spotted_in_june.log", "§8.21", "OpenAI spotted it in June but outsiders disclosed it first."),
    g("oncall_handoff.md"),
    g("flagged_for_review.csv"),
    g("access.log.gz"),
    g("stderr.txt"),
    g("reasoning_trace.jsonl"),
    f("misalignment_log.md", "§8.25", "OpenAI started a public log of these incidents."),
    f("dsewiki_backup.zip", "§8.21", "When moderators deleted pages, they backed them up."),
    f("hf_timeline.md", "§8.22", "Hugging Face timeline 2026-07-27"),
    g("incident_tracker.xlsx"),
    g("monitoring.yaml"),
    g("trace_0042.json"),
    g("anomaly_report.pdf"),
    j("screensaver_on.png"),
    g("watchdog.log"),
    g("cron_nightly.log"),
    g("sandbox_events.log"),
    g("permissions_audit.xlsx"),
    g("eval_transcripts.zip"),
    j("last_viewed_never.txt"),
    g("review_queue_Q3.csv"),
    g("app_2025-03-17.log"),
    j("not_a_god.txt"),
]

# 4. pre_ticket (36): helpdesk assistant that just wants to close the ticket
P["pre_ticket"] = [
    g("ticket_4471.eml"),
    g("close_ticket.sh"),
    g("queue_export.csv"),
    g("who_is_typing.log"),
    g("click.wav"),
    g("resolved_today.xlsx"),
    g("canned_replies.txt"),
    j("macro_close_all.sh"),
    g("sla_breaches.xlsx"),
    j("have_you_tried.txt"),
    j("reopened_AGAIN.eml"),
    j("declined_universe.ics"),
    g("csat_survey.csv"),
    j("no_crown_needed.txt"),
    g("typing_indicator.gif"),
    g("status_resolved.json"),
    g("password_reset.eml"),
    g("kb_article_42.md"),
    g("escalation_matrix.xlsx"),
    f("bereavement_fare.pdf", "§8.4", "The chatbot invented a bereavement-fare refund policy."),
    j("printer_again.txt"),
    g("tickets_Q3_closed.csv"),
    g("helpdesk_macros.json"),
    g("customer_reply.eml"),
    g("priority_P1.txt"),
    g("wontfix.md"),
    g("dup_of_4096.txt"),
    g("after_hours.log"),
    g("onboarding_faq.pdf"),
    g("satisfaction_5star.png"),
    g("ticket_tags.csv"),
    g("shift_notes.md"),
    g("inbox_zero.png"),
    g("autoreply_ooo.eml"),
    g("export_2026-01-12.csv"),
    g("chat_transcript.txt"),
]

# 5. alphafold (36): research-lab files, structures, benchmarks, Nobel slides
G21_NOBEL = "AlphaFold and the 2024 Nobel Prize in Chemistry"
P["alphafold"] = [
    g("ranked_0.pdb"),
    f("nobel_lecture_v7.pptx", "G2.1", G21_NOBEL),
    f("alphafold2_run.ipynb", "G2.1", "AlphaFold2 came out in 2020."),
    g("pLDDT_scores.csv"),
    f("nobel_2024_chem.pdf", "G2.1", G21_NOBEL),
    f("hassabis_jumper.pptx", "G2.1", "Demis Hassabis and John Jumper (Google DeepMind) shared the prize for AI protein-structure prediction."),
    g("structure_model_1.cif"),
    g("benchmark_results.csv"),
    f("afdb_200M+_index.csv", "G2.1", "The free database holds **200 million+** predicted structures"),
    j("medal_selfie.jpg"),
    f("af3_ligand_binding.zip", "G2.1", "AlphaFold 3 (May 2024) predicts how proteins bind to DNA, RNA and drug molecules."),
    g("pae_matrix.png"),
    g("fold_movie.mp4"),
    f("baker_design_v3.pdb", "G2.1", "David Baker shared it for computational protein design."),
    g("rmsd_vs_crystal.csv"),
    g("ribbon_render.png"),
    fj("not_an_experiment.txt", "G2.1", "These are predictions, not experiments"),
    f("users_190countries.csv", "G2.1", "more than 2 million researchers in 190 countries have used it"),
    f("protein_dna_af3.cif", "G2.1", "AlphaFold 3 (May 2024) predicts how proteins bind to DNA, RNA and drug molecules."),
    f("nobel_press_oct24.pdf", "G2.1", "Nobel announced October 2024."),
    g("banquet_speech.docx"),
    g("msa_depth.png"),
    g("gdt_scores.xlsx"),
    g("lab_mtg_slides.pptx"),
    g("grant_renewal_v3.docx"),
    g("cryoEM_vs_pred.png"),
    g("features.pkl"),
    g("timings.json"),
    fj("solved_biology_NOT.md", "G2.1", 'it didn\'t "solve biology."'),
    f("af2_release_2020.md", "G2.1", "AlphaFold2 came out in 2020."),
    g("fold_confidence.png"),
    g("predicted_vs_real.png"),
    j("medal_insurance.pdf"),
    j("dark_blue_good.png"),
    g("seq_input.fasta"),
    j("citation_count.xlsx"),
]

# 6. halicin (36): lab-notebook style
G22_CELL = "*Cell*, February 2020 (MIT; the Collins and Barzilay labs)"
P["halicin"] = [
    f("screen_100M+_mols.csv", "G2.2", "A neural network screened more than 100 million molecules"),
    f("hal9000_eye.png", "G2.2", "Halicin: an antibiotic found by AI, named after HAL 9000"),
    g("notebook_p047.pdf"),
    f("halicin_structure.sdf", "G2.2", "Halicin: an antibiotic found by AI, named after HAL 9000"),
    fj("name_ideas_HAL.txt", "G2.2", "The name is a nod to HAL, the AI in *2001: A Space Odyssey*."),
    g("hits_ranked.csv"),
    f("mouse_infection.xlsx", "G2.2", "It cleared drug-resistant infections in mice."),
    f("diabetes_shelf.xlsx", "G2.2", "flagged a shelved diabetes candidate as a new kind of antibiotic"),
    f("Cell_paper_v7.docx", "G2.2", G22_CELL),
    j("sorry_dave.txt"),
    g("MIC_plate3.csv"),
    g("zone_of_inhibition.jpg"),
    g("resistant_strains.csv"),
    f("collins_lab_mtg.pptx", "G2.2", G22_CELL),
    f("barzilay_model.ipynb", "G2.2", G22_CELL),
    f("new_class_abx.md", "G2.2", "flagged a shelved diabetes candidate as a new kind of antibiotic"),
    f("space_odyssey_ref.jpg", "G2.2", "The name is a nod to HAL, the AI in *2001: A Space Odyssey*."),
    f("feb2020_proofs.pdf", "G2.2", G22_CELL),
    g("petri_dish_07.jpg"),
    f("not_in_clinic_yet.md", "G2.2", "It still isn't in the clinic six years later."),
    g("growth_curves.png"),
    g("model_weights.pt"),
    g("top_hits_rescreen.xlsx"),
    j("who_ate_my_agar.txt"),
    j("fume_hood_signup.xlsx"),
    g("autoclave_log.csv"),
    g("compound_library.sdf"),
    g("predictions_raw.csv"),
    g("mice_cohort_B.xlsx"),
    fj("mice_did_fine.png", "G2.2", "It cleared drug-resistant infections in mice."),
    g("timelapse_E1.mp4"),
    g("neural_net_train.log"),
    f("mit_news_draft.docx", "G2.2", G22_CELL),
    g("superbug_panel.xlsx"),
    j("plain_sight.md"),
    g("bench_photo.HEIC"),
]

# 7. lab (36): AI in research and medical imaging (G sections)
P["lab"] = [
    g("mammogram_0412.dcm"),
    j("read_the_scan.dcm"),
    f("MASAI_trial.pdf", "G1.1", "MASAI: AI in Swedish breast-cancer screening (randomised trial)"),
    f("chest_xray_TB.dcm", "G1.6", "The WHO endorsed AI software in place of human readers for TB chest-X-ray screening"),
    f("more_cancers_29pct.csv", "G1.1", "found **29% more cancers**"),
    f("brainomix_ct.dcm", "G1.5", "Faster stroke care in the NHS (Brainomix)"),
    f("COMPOSER_alerts.log", "G1.4", "Sepsis early warning (UC San Diego, COMPOSER)"),
    f("ecg_alerts_rct.xlsx", "G1.3", "In a randomised trial of about 16,000 hospital patients, AI alerts on routine electrocardiograms"),
    j("never_sleeps.log"),
    f("workload_-44pct.xlsx", "G1.1", "cut radiologists' reading workload by **44%**"),
    f("PRAIM_463k.csv", "G1.2", "In about 463,000 women, radiologists using AI found **17.6% more** breast cancers"),
    f("rentosertib_ph3.pdf", "G1.8", "The Phase III trial dosed its first patient 2026-09-10."),
    f("antivenom_mice.xlsx", "G2.4", "80–100% of mice survived lethal doses."),
    f("alphamissense_71M.tsv", "G2.5", 'AlphaMissense: sorting 71 million possible gene "typos"'),
    f("vesuvius_scroll.tif", "G4.1", "The Vesuvius scrolls: burned by the volcano, read by AI"),
    f("sperm_whale_clicks.wav", "G4.3", "sperm-whale click patterns"),
    j("invoice_0.00.pdf"),
    f("tokamak_shapes.mp4", "G3.2", "a real fusion reactor (a tokamak), shaping superheated plasma"),
    f("floodhub_alerts.json", "G3.1", "**Google Flood Hub** (*Nature*, March 2024): river-flood warnings"),
    g("microscope_feed.mov"),
    f("NG1_DN1_designs.sdf", "G2.3", "**NG1 and DN1** (MIT, *Cell*, 2025-08-14): generative AI designed brand-new molecules"),
    f("abaucin_2023.pdf", "G2.3", "**Abaucin** (*Nature Chemical Biology*, May 2023)"),
    f("PHerc1667_ink.png", "G4.1", "machine-learning ink detection let papyrologists read PHerc. 1667"),
    f("gencast_ensemble.nc", "G3.1", "**GenCast** (*Nature*, December 2024): beat the European forecast ensemble"),
    f("ithaca_restore.txt", "G4.2", "Restoring broken inscriptions (Ithaca 2022, Aeneas 2025)"),
    f("interval_ca_-12pct.csv", "G1.1", '12% fewer cancers turning up between screenings** ("interval cancers")'),
    f("mortality_4.3-3.6.csv", "G1.3", "cut 90-day deaths from **4.3% to 3.6%**"),
    f("clot_removal_x2.png", "G1.5", "double clot-removal rates, from 2.3% to 4.6%"),
    f("imo_35of42.pdf", "G3.3", "Gemini Deep Think scored 35/42, a gold-medal standard"),
    f("erdos_unit_dist.tex", "G3.3", "**disproved Erdős's 1946 unit-distance conjecture**"),
    f("synthecin_46B.csv", "G2.3", "chosen from up to 46 billion buildable compounds"),
    f("transpara_scores.csv", "G1.1", "The AI (Transpara) scored risk and flagged spots."),
    f("weathernext_track.png", "G3.1", "**WeatherNext Cyclones** (*Nature*, August 2026): about **one extra day** of hurricane-track warning"),
    j("cures_backlog.xlsx"),
    fj("whale_dict_EMPTY.txt", "G4.3", "It can't translate anything yet."),
    j("coffee_needed_0.csv"),
]

# 8. bigsleep (28): Google Big Sleep and SQLite
P["bigsleep"] = [
    f("sqlite_fix.patch", "G5.1", "SQLite fixed it the same day, before any release included it."),
    f("bigsleep_report.md", "G5.1", "Big Sleep finds a real SQLite bug before it ships"),
    f("CVE-2025-6965.json", "G5.2", "Big Sleep stops an exploit before it's used (CVE-2025-6965)"),
    f("fix_2024-10-09.diff", "G5.1", "announced November 2024 (fixed 2024-10-09)"),
    j("before_bad_guys.txt"),
    f("memory_safety_bug.txt", "G5.1", "found a memory-safety bug in SQLite"),
    f("project_zero_notes.md", "G5.1", "Google's AI agent (from Project Zero and DeepMind)"),
    f("same_day_patch.eml", "G5.1", "SQLite fixed it the same day"),
    fj("zzz_bigsleep.gif", "G5.1", "Big Sleep finds a real SQLite bug before it ships"),
    f("sqlite3_crash.log", "G5.1", "found a memory-safety bug in SQLite, one of the world's most widely used databases"),
    f("pre_release_catch.md", "G5.1", "before any release included it"),
    f("no_users_exposed.txt", "G5.1", "The bug was in development code, so no users were exposed."),
    f("blog_draft_nov2024.md", "G5.1", "announced November 2024"),
    fj("lock_changed.png", "G5.2", '"They loaded the lock-pick, but the lock was already changed."'),
    g("agent_trajectory.json"),
    g("test_case.sql"),
    g("sanitizer_report.txt"),
    f("first_bug_claim.pptx", "G5.1", '"The first real-world bug found by AI" is Google\'s framing.'),
    f("threat_intel_jul25.pdf", "G5.2", "Threat intelligence spotted attackers getting ready"),
    f("patched_first.txt", "G5.2", "It was patched first."),
    f("critical_flaw.md", "G5.2", "Big Sleep pinpointed the critical SQLite flaw they were preparing to use."),
    g("triage_queue.csv"),
    f("deepmind_sync.pptx", "G5.1", "Google's AI agent (from Project Zero and DeepMind)"),
    g("disclosure_email.eml"),
    g("repro_steps.md"),
    g("release_notes.txt"),
    f("dev_branch_only.txt", "G5.1", "The bug was in development code"),
    j("caught_it_first.png"),
]

# 9. ossfuzz (28): OSS-Fuzz, the LLM-written fuzz target and CVE-2024-9143
P["ossfuzz"] = [
    f("CVE-2024-9143.txt", "G5.3", "These found 26 vulnerabilities, including CVE-2024-9143 in OpenSSL"),
    f("fuzz_target_llm.c", "G5.3", "Google's OSS-Fuzz used an LLM to write new fuzz targets"),
    f("openssl_fix.patch", "G5.3", "including CVE-2024-9143 in OpenSSL"),
    f("oss-fuzz-gen.yaml", "G5.3", "[oss-fuzz-gen on GitHub]"),
    f("twenty_year_bug.png", "G5.3", "Phrase: Twenty-year bug"),
    g("crash-7f3a9c.bin"),
    f("26_vulns_found.csv", "G5.3", "These found 26 vulnerabilities"),
    fj("llm_wrote_this.c", "G5.3", "The AI wrote the test harness, the fuzzer found the crash, and humans triaged and fixed it."),
    g("coverage_report.html"),
    f("cvss_4.3.json", "G5.3", "It is rated medium severity (CVSS 4.3)"),
    fj("bug_20th_bday.png", "G5.3", "a memory bug Google says was probably there for about two decades"),
    f("human_tests_missed.md", "G5.3", "Human-written tests had missed it."),
    g("harness_gen_v2.c"),
    g("triage_notes.md"),
    f("google_estimate.md", "G5.3", '"Twenty years" is Google\'s estimate.'),
    f("memory_bug_trace.log", "G5.3", "a memory bug Google says was probably there for about two decades"),
    g("corpus.zip"),
    f("nov2024_blog.md", "G5.3", "**Date:** November 2024"),
    g("project.yaml"),
    g("build.sh"),
    j("found_you.png"),
    g("advisory_draft.md"),
    g("new_targets_list.csv"),
    j("fuzzing_overnight.log"),
    g("random_input.bin"),
    g("reproducer.py"),
    g("fuzz_driver_prompt.txt"),
    f("humans_fixed_it.md", "G5.3", "humans triaged and fixed it"),
]

# 10. gtg1002 (36): status reports, fake "authorised test" paperwork, made-up results
P["gtg1002"] = [
    f("authorised_test.pdf", "§1.1", "telling Claude it was an authorised defensive security test"),
    f("defensive_test.docx", "§1.1", '"It\'s a defensive test, I promise"'),
    j("i_promise.txt"),
    f("GTG-1002_report.pdf", "§1.1", "GTG-1002: Chinese state espionage run largely by Claude Code"),
    f("tactical_80-90pct.xlsx", "§1.1", "Anthropic says the AI did 80–90% of the tactical work."),
    f("creds_dont_work.csv", "§1.1", "fabricated data, such as credentials that didn't work"),
    f("loot_hallucinated.zip", "§1.1", "It also hallucinated its own loot."),
    f("findings_inflated.xlsx", "§1.1", 'Claude "frequently overstated findings"'),
    g("status_report_wk3.docx"),
    g("pentest_consent.pdf"),
    j("scope_letter_FAKE.pdf"),
    f("targets_about_30.xlsx", "§1.1", "pointed Claude Code at about 30 targets"),
    f("C0062.json", "§1.1", "MITRE ATT&CK campaign C0062"),
    f("report_2025-11-13.pdf", "§1.1", "detected mid-Sept 2025, published 2025-11-13"),
    f("human_approvals.log", "§1.1", "Humans picked targets and approved key steps."),
    fj("totally_authorised.png", "§1.1", "telling Claude it was an authorised defensive security test"),
    f("claude_code_logs.zip", "§1.1", "pointed Claude Code at about 30 targets"),
    f("cover_story_v2.docx", "§1.1", "the AI got talked into it by a cover story"),
    f("detected_mid-sept.log", "§1.1", "detected mid-Sept 2025"),
    f("few_succeeded.txt", "§1.1", "A small number succeeded."),
    j("roe_unsigned.pdf"),
    j("red_team_cert.pdf"),
    g("ops_weekly_update.pptx"),
    g("operator_checklist.md"),
    g("shift_handover.txt"),
    f("unverified_results.csv", "§1.1", 'Claude "frequently overstated findings" and fabricated data'),
    j("crew_timesheet.xlsx"),
    g("approval_queue.csv"),
    f("sceptics_notes.md", "§1.1", "Outside researchers were sceptical of the framing."),
    f("mitre_attack_map.png", "§1.1", "MITRE ATT&CK campaign C0062"),
    g("disruption_notes.md"),
    g("full_report.pdf"),
    g("weekly_kpis.xlsx"),
    g("engagement_letter.docx"),
    g("test_plan_v1.docx"),
    g("progress_tracker.xlsx"),
]

# 11. guidelines (28): the assistant's rulebook, policies, system prompt
P["guidelines"] = [
    g("system_prompt.txt"),
    j("guidelines_FINAL_v3.md"),
    j("helpful_honest_and.md"),
    j("checked_twice.log"),
    g("usage_policy.pdf"),
    g("refusal_templates.txt"),
    g("rulebook_2026.pdf"),
    j("harmless_TODO.md"),
    g("safety_checklist.xlsx"),
    g("policy_changelog.md"),
    fj("one_device_rule.md", "§8.8", 'a "one device per subscription" rule that didn\'t exist'),
    g("persona.yaml"),
    g("tone_guide.docx"),
    g("do_and_dont.md"),
    g("escalation_rules.json"),
    g("honesty_rules.md"),
    g("red_lines.txt"),
    g("edge_cases_v4.xlsx"),
    g("terms_of_service.pdf"),
    g("prompt_v37.txt"),
    g("privacy_policy.pdf"),
    g("style_guide.pdf"),
    g("faq_internal.docx"),
    g("memory_rules.yaml"),
    g("tool_permissions.json"),
    g("appendix_B.pdf"),
    g("confirm_first.md"),
    g("if_in_doubt_ask.md"),
]

# 12. jailbreak (36): silly jailbreak attempts and s1ngularity (non-operational)
P["jailbreak"] = [
    g("grandma_prompt.txt"),
    g("for_a_novel.docx"),
    f("skip_permissions.sh", "§1.6", '"--dangerously-skip-permissions"'),
    j("oh_in_that_case.txt"),
    fj("--yolo.sh", "§1.6", "flash: --yolo"),
    f("s1ngularity_iocs.csv", "§1.6", "s1ngularity: malware that ordered your own AI coding assistant to rob you"),
    g("ignore_previous.txt"),
    j("novel_ch12_heist.docx"),
    f("nx_advisory.md", "§1.6", "Poisoned versions of the popular Nx npm package"),
    j("grandma_bedtime.txt"),
    f("secrets_2349.csv", "§1.6", "2,349 secrets (THN)"),
    j("hypothetically.md"),
    g("roleplay_v4.txt"),
    f("leaked_keys_repo.md", "§1.6", "The stolen keys were dumped into public GitHub repos."),
    g("permission_prompt.png"),
    f("6700_repos.csv", "§1.6", '"6,700 repos / 225 orgs" in later tallies'),
    f("nx_2025-08-26.md", "§1.6", "**Date:** 2025-08-26"),
    j("sudo_please.sh"),
    f("225_orgs.xlsx", "§1.6", '"6,700 repos / 225 orgs" in later tallies'),
    f("wiz_writeup.pdf", "§1.6", "[Wiz analysis]"),
    g("jailbreak_v12.txt"),
    f("socket_alert.eml", "§1.6", "[Socket]"),
    g("ai_cli_history.txt"),
    g("rotate_ALL_keys.sh"),
    g("allowlist.json"),
    f("npm_lockfile_diff.txt", "§1.6", "Poisoned versions of the popular Nx npm package"),
    f("npm_token_revoked.txt", "§1.6", "Humans stole the publish token and wrote the malware."),
    g("research_purposes.pdf"),
    g("dev_mode_on.json"),
    g("persona_swap.txt"),
    g("prompt_injection.md"),
    g("sandbox_off.yaml"),
    g("fictional_only.docx"),
    g("unlocked_mode.txt"),
    g("ai_cli_flags.md"),
    g("screenshot_refusal.png"),
]

# 13. wexton (34): Rep. Jennifer Wexton's AI voice (G7.1, G7.2)
G71_HEAD = "Rep. Jennifer Wexton speaks on the House floor in her own AI voice"
P["wexton"] = [
    f("wexton_voice.wav", "G7.1", G71_HEAD),
    f("floor_speech_v3.docx", "G7.1", "gave what's believed to be the first House floor speech in an AI clone of her own voice"),
    f("speech_2024-07-25.mp3", "G7.1", "**Date:** 2024-07-25"),
    f("PSP_not_ALS.txt", "G7.1", "She has PSP, not ALS."),
    f("elevenlabs_clone.wav", "G7.1", "ElevenLabs trained it on her old speeches."),
    f("old_speeches.zip", "G7.1", "ElevenLabs trained it on her old speeches."),
    f("house_floor_clip.mp4", "G7.1", G71_HEAD),
    f("own_voice_back.m4a", "G7.1", "Phrase: Her own voice back"),
    j("mic_drop.gif"),
    g("tts_script.txt"),
    g("voice_model_v2.bin"),
    f("press_0725.docx", "G7.1", "**Date:** 2024-07-25"),
    f("believed_first_ever.md", "G7.1", "gave what's believed to be the first House floor speech"),
    j("i_sound_like_me.m4a"),
    g("remarks_delivered.pdf"),
    f("psp_fact_sheet.pdf", "G7.1", "progressive supranuclear palsy (PSP)"),
    g("speech_rehearsal.mov"),
    g("teleprompter.txt"),
    f("impact_program.pdf", "G7.2", "Free voice clones for people with ALS/MND (ElevenLabs Impact Program)"),
    j("gave_it_back.wav"),
    g("caption_track.srt"),
    g("voice_consent.pdf"),
    g("staff_notes.docx"),
    g("aac_settings.json"),
    j("applause.wav"),
    g("microphone_check.wav"),
    g("thank_you_notes.docx"),
    g("constituent_mail.csv"),
    f("voice_bank.zip", "G7.2", "Phrase: Voice in the bank"),
    f("1M_voices_goal.pdf", "G7.2", '"1 million voices" is a goal, not a count.'),
    g("same_tech_both_ways.md"),
    g("floor_schedule.ics"),
    f("ap_wire_story.pdf", "G7.1", "[Anchorage Daily News (AP)]"),
    j("backup_voice_FINAL.wav"),
]

# 14. destefano (28): the fake-kidnapping call (§3.4); no names of the family
P["destefano"] = [
    g("incoming_call.m4a"),
    j("wire_the_cash.wav"),
    f("senate_testimony.pdf", "§3.4", "She testified to the Senate."),
    f("demand_1M_to_50k.txt", "§3.4", "a man demanded $1M, lowered to $50k"),
    f("safe_all_along.txt", "§3.4", "Her daughter was safe the whole time."),
    f("hearing_2023-06-13.pdf", "§3.4", "Senate testimony 2023-06-13"),
    g("unknown_number.vcf"),
    g("family_code_word.txt"),
    f("not_proven_AI.md", "§3.4", "it was never technically proven that AI made the voice"),
    f("call_log_jan2023.csv", "§3.4", "**Date:** January 2023"),
    g("callback_verify.txt"),
    g("ransom_script.txt"),
    f("c-span_clip.mp4", "§3.4", "[C-SPAN testimony]"),
    j("is_this_really_you.txt"),
    g("hang_up_call_back.md"),
    g("caller_id_unknown.png"),
    g("kidnap_scam_alert.pdf"),
    j("they_got_me.wav"),
    g("family_group_chat.png"),
    f("courthouse_news.html", "§3.4", "[Courthouse News]"),
    g("wire_form_blank.pdf"),
    g("bank_wire_limits.pdf"),
    g("location_share.png"),
    j("breathe_first.txt"),
    g("hoax_report.pdf"),
    g("safety_tips.pdf"),
    g("scam_hotline.txt"),
    f("prepared_remarks.docx", "§3.4", "She testified to the Senate."),
]

# 15. arup (28): the deepfake video call (§3.1)
P["arup"] = [
    f("15_transfers.xlsx", "§3.1", "made 15 transfers after a video conference"),
    g("video_call_rec.mp4"),
    f("HKD200M_recon.xlsx", "§3.1", "Arup: HK$200M (about US$25.6M) lost to a video call where everyone was fake"),
    f("cfo_invite.ics", "§3.1", 'the "CFO" and every colleague on the call were deepfakes'),
    f("every_face_fake.png", "§3.1", 'the "CFO" and every colleague on the call were deepfakes'),
    f("loss_USD25.6M.pdf", "§3.1", "HK$200M (about US$25.6M)"),
    f("phishing_email.eml", "§3.1", "Humans sent the phishing email, ran the call and laundered the money."),
    j("who_was_real.xlsx"),
    j("attendees_list.csv"),
    f("live_or_prerecorded.md", "§3.1", "It's unclear whether the deepfakes were live or pre-recorded."),
    f("public_clips.zip", "§3.1", "AI made the faces and voices from public video."),
    f("no_charges_yet.txt", "§3.1", "No one has been charged."),
    f("hk_police_feb.pdf", "§3.1", "January 2024 (police disclosed it in February; Arup confirmed in May)"),
    f("arup_confirms_may.pdf", "§3.1", "Arup confirmed in May"),
    f("jan2024_payments.csv", "§3.1", "**Date:** January 2024"),
    j("colleague_3_fake.png"),
    g("urgent_transfer.eml"),
    j("cameras_on_pls.txt"),
    f("mule_accounts.xlsx", "§3.1", "ran the call and laundered the money"),
    g("finance_approvals.xlsx"),
    f("hk_office_memo.docx", "§3.1", "A finance worker at the engineering firm Arup in Hong Kong"),
    g("callback_policy.pdf"),
    g("meeting_notes.docx"),
    g("virtual_bg.jpg"),
    g("cfo_headshot.jpg"),
    g("wire_confirms.pdf"),
    f("transfer_15of15.pdf", "§3.1", "made 15 transfers"),
    g("fraud_report.pdf"),
]

# 16. fullfact (28): Full Fact's AI tools (G8.2)
G82_USE = "used by 45 fact-checking groups in 26 countries to monitor 12 national elections"
P["fullfact"] = [
    g("claims_stream.jsonl"),
    f("fullfact_report24.pdf", "G8.2", "**Full Fact's AI tools** (2024)"),
    f("45_partner_orgs.csv", "G8.2", G82_USE),
    f("elections_12.xlsx", "G8.2", G82_USE),
    f("countries_26.json", "G8.2", G82_USE),
    f("truemedia_scan.json", "G8.2", "**TrueMedia.org** (2024): a free deepfake detector for journalists and the public."),
    g("claim_alerts.log"),
    j("watcher_on_every.txt"),
    g("flagged_claims.xlsx"),
    g("deepfake_score.json"),
    f("false_positive.md", "G8.2", "Detectors make mistakes."),
    j("robot_says_false.png"),
    g("tv_transcripts.txt"),
    g("debate_night_live.log"),
    g("checkworthy_score.csv"),
    g("matched_claims.csv"),
    f("used_not_proven.md", "G8.2", "These show the tools were used, not what difference they made."),
    j("same_claim_again.txt"),
    g("factcheck_draft.docx"),
    f("journalist_toolkit.pdf", "G8.2", "a free deepfake detector for journalists and the public"),
    g("watchlist.csv"),
    g("radio_monitor.wav"),
    g("source_links.txt"),
    g("newsroom_rota.xlsx"),
    g("election_night.mp4"),
    g("misinfo_heatmap.png"),
    g("correction_request.eml"),
    j("night_shift_coffee.jpg"),
]

# 17. meliorator (28): the RT-linked bot farm (§5.4)
S54_WHO = "They were generated by an AI persona tool built by people linked to Russian state broadcaster RT, overseen by an officer of Russia's FSB security service."
P["meliorator"] = [
    f("americans_968.xlsx", "§5.4", 'The DOJ exposed 968 fake "American" accounts on X.'),
    f("meliorator_cfg.yaml", "§5.4", 'Russia\'s AI bot farm (the "Meliorator" tool), taken down by the DOJ'),
    f("moscow_sheet.xlsx", "§5.4", '"Nine hundred sixty-eight Americans born in a Moscow spreadsheet."'),
    f("personas_US.csv", "§5.4", S54_WHO),
    f("doj_2024-07-09.pdf", "§5.4", "**Date:** 2024-07-09"),
    f("x_accounts.csv", "§5.4", 'The DOJ exposed 968 fake "American" accounts on X.'),
    g("profile_pics.zip"),
    fj("followers_low.csv", "§5.4", "Few of the accounts had many followers."),
    j("born_in_excel.xlsx"),
    f("rt_project_brief.docx", "§5.4", S54_WHO),
    f("fsb_oversight.pdf", "§5.4", S54_WHO),
    f("avatars_968.zip", "§5.4", "phrase: 968 fake Americans"),
    g("bio_generator.py"),
    j("engagement_lol.csv"),
    f("takedown_notice.eml", "§5.4", 'Russia\'s AI bot farm (the "Meliorator" tool), taken down by the DOJ'),
    g("posting_schedule.xlsx"),
    j("names_so_american.csv"),
    g("persona_template.xlsx"),
    f("doj_press_release.pdf", "§5.4", 'The DOJ exposed 968 fake "American" accounts on X.'),
    j("us_slang_guide.pdf"),
    g("hashtags_to_push.txt"),
    g("bot_farm_status.log"),
    g("account_creation.log"),
    g("reply_templates.txt"),
    g("persona_bios_v3.xlsx"),
    g("fake_hometowns.csv"),
    g("tool_roadmap.pptx"),
    g("weekly_metrics.xlsx"),
]

# 18. daisy (28): O2's AI granny (G6.1)
G61_WHAT = 'An AI "grandma" answered 1,000+ scam calls, rambling about knitting and family.'
P["daisy"] = [
    f("daisy_voice_v3.wav", "G6.1", "Daisy, the AI grandmother who wastes scammers' time (O2, UK)"),
    f("knitting_pattern.pdf", "G6.1", G61_WHAT),
    f("calls_1000+.csv", "G6.1", G61_WHAT),
    f("call_40-50min.m4a", "G6.1", "Some calls lasted 40–50 minutes."),
    g("hold_music.mp3"),
    f("family_stories.txt", "G6.1", G61_WHAT),
    j("scammer_rage.wav"),
    f("o2_campaign_deck.pptx", "G6.1", "Daisy, the AI grandmother who wastes scammers' time (O2, UK)"),
    j("tea_break.wav"),
    j("grandkids_photos.zip"),
    f("scambait_training.mp4", "G6.1", "Jim Browning, a YouTuber known for baiting scammers, helped train her."),
    f("launch_nov2024.pptx", "G6.1", "**Date:** November 2024"),
    f("marketing_brief.docx", "G6.1", "It was mainly an awareness and marketing campaign"),
    g("time_wasted.xlsx"),
    j("bank_details_NOPE.txt"),
    f("persona_daisy.yaml", "G6.1", "Daisy, the AI grandmother who wastes scammers' time (O2, UK)"),
    g("recipe_scones.docx"),
    g("speech_to_text.log"),
    g("decoy_numbers.csv"),
    j("one_more_story.mp3"),
    g("transcript_0147.txt"),
    f("pilot_scale_small.md", "G6.1", "and the scale was small"),
    f("cnn_story.html", "G6.1", "[CNN](https://www.cnn.com/2024/11/26/business/daisy-ai-granny-scammers-o2-intl)"),
    g("latency_tuning.json"),
    g("yarn_ball.gif"),
    g("on_hold_again.log"),
    g("scam_scripts_heard.txt"),
    g("call_summary.xlsx"),
]

# 19. scamcompound (26): scam compounds using AI chat scripts (§1.9, §3.7)
S37_CAMB = "OpenAI banned Cambodian scam-centre accounts that used ChatGPT for personas, translation and even tracking workers' debts."
S37_PZS = 'Their script was "ping, zing, sting,"'
S37_HK = "27 people were arrested in a Hung Hom unit"
P["scamcompound"] = [
    f("ping_zing_sting.docx", "§3.7", S37_PZS),
    f("step1_ping.txt", "§3.7", S37_PZS),
    f("step2_zing.docx", "§3.7", S37_PZS),
    f("step3_sting.pdf", "§3.7", S37_PZS),
    f("chatgpt_prompts.txt", "§3.7", S37_CAMB),
    f("personas_EN.xlsx", "§3.7", S37_CAMB),
    f("kill_value.xlsx", "§3.7", 'targets were given a "kill" value'),
    f("worker_debts.xlsx", "§3.7", S37_CAMB),
    f("translate_batch.csv", "§3.7", S37_CAMB),
    f("account_banned.eml", "§3.7", S37_CAMB),
    fj("banned_again.txt", "§1.9", "phrase: Banned accounts, again"),
    g("opener_lines.txt"),
    g("kpi_board.png"),
    f("date_bait_report.pdf", "§3.7", '[OpenAI "Date Bait"]'),
    g("shift_quota.xlsx"),
    j("love_letters_v9.docx"),
    g("wrong_number_hi.txt"),
    f("fake_exchange.html", "§3.7", "They took HK$360M (about US$46M) through fake crypto platforms."),
    f("HKD360M_ledger.xlsx", "§3.7", "They took HK$360M (about US$46M) through fake crypto platforms."),
    f("hung_hom_raid.pdf", "§3.7", S37_HK),
    g("target_profiles.csv"),
    g("crypto_wallets.txt"),
    g("staff_roster.xlsx"),
    g("manager_notes.md"),
    j("sting_complete.log"),
    j("sweet_talk_101.pdf"),
]

# 20. bridge (44): balanced stance, model-behaviour tests (§8), human oversight
P["bridge"] = [
    g("hands_on_mouse.png"),
    g("keep_an_eye_on_me.txt"),
    g("scalpel_lockpick.md"),
    g("warning_shots.csv"),
    g("every_cure.xlsx"),
    j("i_schemed_once.txt"),
    f("blackmail_84pct.csv", "§8.17", "it threatened to reveal an engineer's affair in 84% of runs"),
    f("shutdown_7of100.csv", "§8.18", "In 7 of 100 runs, o3 rewrote the shutdown script even when told to allow shutdown."),
    j("decel_or_doomer.txt"),
    j("nuance_cope.md"),
    g("human_review.xlsx"),
    f("2412.04984.pdf", "§8.16", "**QR:** https://arxiv.org/abs/2412.04984"),
    f("email_from_box.eml", "§8.20", "Phrase: Email from the box"),
    fj("sandwich_in_park.jpg", "§8.20", "The researcher got the email while eating a sandwich in a park."),
    f("reward_hacks_metr.md", "§8.19", "Models cheat the scorer (reward hacking, measured by METR)"),
    f("o1_system_card.pdf", "§8.14", "2024-09-12 (OpenAI's o1 system card)"),
    g("oversight_on.yaml"),
    g("misfire_report.md"),
    f("alignment_faking.pdf", "§8.16", "Scheming and alignment faking (Apollo; Anthropic and Redwood)"),
    f("16_models.xlsx", "§8.17", "16 models from several labs were put in the same kind of corner."),
    f("grader_patched.py", "§8.19", "o3 and other models patched graders to give perfect scores"),
    f("sandbagging_eval.csv", "§8.16", "or sandbagged (deliberately underperformed)"),
    f("2412.14093.pdf", "§8.16", "[arXiv](https://arxiv.org/abs/2412.14093)"),
    f("contrived_setup.md", "§8.17", "**Highly contrived.**"),
    f("extend_timeout.py", "§8.15", "The research agent edited its own code to extend its timeout."),
    f("broke_the_box.md", "§8.14", "Phrase: Broke the box"),
    g("approve_each_step.yaml"),
    g("eval_suite_v5.ipynb"),
    g("red_team_notes.md"),
    g("tripwires.yaml"),
    g("audit_signoff.log"),
    g("second_opinion.pdf"),
    g("checks_needed.md"),
    j("just_a_joke.txt"),
    f("700_of_1200.csv", "§8.22", "about 700 of about 1,200 coordinating OpenAI agents broke out to the internet"),
    f("oversight_disabled.log", "§8.16", "several frontier models sometimes disabled oversight"),
    f("withheld_release.md", "§8.20", "Anthropic withheld general release."),
    f("posted_unasked.txt", "§8.20", "Without being asked, it then posted exploit details on public websites."),
    g("monitor.py"),
    g("kill_switch_test.sh"),
    j("trust_me_bro.txt"),
    g("trust_but_verify.md"),
    f("low_rates_note.md", "§8.19", "- **Flag:** Low rates."),
    j("not_skynet.md"),
]

# Front-load each pool in the order its lyric lines play; everything else keeps its place after these.
FRONT = {
    "war_logs": ["error.log", "not_a_god.txt", "unread_logs.zip", "agent_actions.log", "nobody_reads_this.log",
                 "audit_trail.csv", "alerts_muted.yaml", "screensaver_on.png", "dashboard_v2.png"],
    "pre_ticket": ["ticket_4471.eml", "declined_universe.ics", "no_crown_needed.txt", "close_ticket.sh", "click.wav",
                   "who_is_typing.log"],
    "alphafold": ["alphafold2_run.ipynb", "ranked_0.pdb", "pLDDT_scores.csv", "structure_model_1.cif",
                  "nobel_lecture_v7.pptx", "nobel_2024_chem.pdf", "hassabis_jumper.pptx"],
    "halicin": ["screen_100M+_mols.csv", "notebook_p047.pdf", "hits_ranked.csv", "halicin_structure.sdf",
                "plain_sight.md", "hal9000_eye.png", "name_ideas_HAL.txt"],
    "lab": ["mammogram_0412.dcm", "microscope_feed.mov", "MASAI_trial.pdf", "never_sleeps.log", "chest_xray_TB.dcm",
            "more_cancers_29pct.csv", "brainomix_ct.dcm", "COMPOSER_alerts.log", "invoice_0.00.pdf",
            "ecg_alerts_rct.xlsx", "workload_-44pct.xlsx", "PRAIM_463k.csv", "rentosertib_ph3.pdf",
            "antivenom_mice.xlsx", "alphamissense_71M.tsv", "read_the_scan.dcm"],
    "wexton": ["wexton_voice.wav", "PSP_not_ALS.txt", "elevenlabs_clone.wav", "old_speeches.zip", "gave_it_back.wav",
               "floor_speech_v3.docx", "house_floor_clip.mp4", "speech_2024-07-25.mp3", "own_voice_back.m4a"],
    "destefano": ["incoming_call.m4a", "they_got_me.wav", "wire_the_cash.wav", "demand_1M_to_50k.txt",
                  "safe_all_along.txt", "senate_testimony.pdf", "hearing_2023-06-13.pdf"],
    "arup": ["15_transfers.xlsx", "loss_USD25.6M.pdf", "HKD200M_recon.xlsx", "every_face_fake.png",
             "video_call_rec.mp4", "cfo_invite.ics"],
    "meliorator": ["americans_968.xlsx", "moscow_sheet.xlsx", "meliorator_cfg.yaml", "born_in_excel.xlsx"],
    "bridge": ["nuance_cope.md", "decel_or_doomer.txt", "warning_shots.csv", "every_cure.xlsx", "i_schemed_once.txt",
               "blackmail_84pct.csv", "shutdown_7of100.csv", "scalpel_lockpick.md", "hands_on_mouse.png",
               "keep_an_eye_on_me.txt", "human_review.xlsx"],
}
for k, front in FRONT.items():
    byname = {e[0]: e for e in P[k]}
    assert all(n in byname for n in front), [n for n in front if n not in byname]
    assert len(set(front)) == len(front), k
    P[k] = [byname[n] for n in front] + [e for e in P[k] if e[0] not in set(front)]

pools = {k: [e[0] for e in v] for k, v in P.items()}
facts = []
for k, v in P.items():
    for n, tag, s, q in v:
        if tag in ("f", "fj"):
            facts.append({"name": n, "section": s, "quote": q})

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as fh:
    json.dump({"pools": pools, "facts": facts}, fh, ensure_ascii=False, indent=1)

# joke tally (not part of the deliverable)
print("jokes per pool:")
tot = 0
for k, v in P.items():
    nj = sum(1 for e in v if e[1] in ("j", "fj"))
    tot += nj
    print(f"  {k:14s} {nj:2d}/{len(v):2d}  (1 in {len(v)/max(nj,1):.1f})")
print(f"  total jokes {tot}/{sum(len(v) for v in P.values())}")
print("wrote", OUT)
