import os
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))   # repo root
# 3.2 lip-sync: loudness of the Demucs vocal stem at 60 fps, as one digit 0-9 per frame, for prototype/voice.js
import numpy as np, librosa
SR=22050; HOP=128
v,_=librosa.load('sep4/htdemucs/vocals.wav',sr=SR,mono=True)
r=librosa.feature.rms(y=v,frame_length=512,hop_length=HOP,center=True)[0]
ft=np.arange(len(r))*HOP/SR
dur=len(v)/SR; n=int(np.ceil(dur*60))
tt=np.arange(n)/60
x=np.interp(tt,ft,r)
db=20*np.log10(x+1e-6)
ref=np.percentile(db[db>-50],97)          # loud sung vowels
from scipy.ndimage import maximum_filter1d
loc=np.minimum(maximum_filter1d(db,size=25),ref)   # local peak over ~0.4 s, so dips between syllables close the mouth
gate=np.clip((db-(ref-38))/8,0,1)                  # silence (38+ dB below the loud vowels) stays shut
lv=np.clip((db-(loc-16))/16,0,1)*gate            # 16 dB range below the local peak
q=np.round(lv*9).astype(int)
s=''.join(map(str,q))
open(os.path.join(ROOT, 'render', 'voice.js'),'w').write(
 "// Vocal loudness for the assistant's lip-sync (draft 3, detail 3.2): the Demucs vocal stem of take1.wav, RMS in 23 ms\n"
 "// windows at 60 fps, mapped to 0-9 over the 16 dB below the local peak (so syllables open and close). Generated by audio/analysis/voice_env.py.\n"
 f"window.VOICE={{fps:60,v:'{s}'}};\n")
hist=np.bincount(q,minlength=10); print('frames',n,'hist',hist.tolist())
for a,b in [(1.86,5.48),(42.2,45.5),(186.9,187.06),(245.6,247.9)]:
    print(a,b,s[int(a*60):int(b*60)][:120])
